cask_args appdir: '/Applications'

tap 'touchbistro/tap'

cask 'aws-vault-binary'
cask 'claude'
cask 'font-jetbrains-mono-nerd-font'
cask 'rectangle'
cask 'visual-studio-code'

brew 'awscli'
brew 'bat'
brew 'cloudflared'
brew 'cloc'
brew 'eza'
brew 'dive'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'htop'
brew 'jless'
brew 'jq'
brew 'lazydocker'
brew 'magic-wormhole'
brew 'mise'
brew 'pandoc'
brew 'pgcli'
brew 'pstree'
brew 'ripgrep'
brew 'shellcheck'
brew 'sqlite'
brew 'shfmt'
brew 'starship'
brew 'tldr'
brew 'touchbistro/tap/tb'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'yt-dlp'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
